### ISSUE TITLE
Exclude some loots

### ISSUE THREAD

**Issue by clem193** [Saegusae/loot#2]
Hi Goose,
Can you add lines to Exclude :
- Mystics HP / MP Motes
- HP Motes Dropping on IoD BAMs / Normal Monsters

Also Maybe smthing to stop retrying to pick a loot when "Isn't yours" in auto mode ? (idk if it's possible tho xD)

**Comment by Saegusae** [comment]
The "this isn't yours" issue was fixed with a PR, and you can add HP/MP motes to the config blacklist, its why I made one.
